"""Add Comment

Revision ID: 587197137b51
Revises: 7d6a4f8fd761
Create Date: 2026-01-23 15:16:54.643051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587197137b51'
down_revision = '7d6a4f8fd761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=250), nullable=False),
    sa.Column('todo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['todo_id'], ['todo_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
